extraction:
  cpp:
    after_prepare: 
      - python report.py 56
  cobol:
    after_prepare: 
      - python report.py 56
  csharp:
    after_prepare: 
      - python report.py 56
  java:
    after_prepare: 
      - python report.py 56
  javascript:
    after_prepare: 
      - python report.py 56
  python:
    after_prepare: 
      - python report.py 56
